package cluedo.character;

public enum CardName{
	KITCHEN, BALL_ROOM, CONSERVATORY, DINING_ROOM, BILLARD_ROOM,
	LIBRARY, LOUNGE, HALL, STUDY, MRS_WHITE_C, MISS_SCARLET_C, COLONEL_MUSTARD_C, REVEREND_GREEN_C,
	MRS_PEACOCK_C, PROFESSOR_PLUM_C, CANDLESTICK, DAGGER, LEAD_PIPE, REVOLVER, ROPE, SPANNER
}


